version: "3"

# Define the services/containers to be run
services:
  server:
    build: .
    ports:
      - "80:8080"
    environment:
      DB_BASE_URL: "database"
      DB_PORT: "27017"
    links:
      - database

  database:
    image: mongo
    ports:
      - "27017:27017"
